configuration:
  template_dir:
  - "git://github.com/moremoban/pypi-mobans.git?submodule=true&brach=dev!/templates"
  - ".moban.d"
  configuration: brython-pack.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - test.sh: test.script.jj2
  - "brython_pack/_version.py": "_version.py.jj2"
  - "brython_pack/__init__.py": "__init__.py.jj2"
  - .gitignore: gitignore.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
